
version: '3.9'

services:
  processor:
    image: devintyler2626/tesalate-processor:latest
    build: .
    env_file:
      - .env
    environment:
      - APP_TYPE=producer
    depends_on:
      - mongodb
      - redis
    links:
      - redis
      - mongodb
    volumes:
      - ./logs:/home/node/app/logs
    networks:
      - node-network

  producer:
    image: devintyler2626/tesalate-processor:latest
    build: .
    env_file:
      - .env
    environment:
      - APP_TYPE=producer
    depends_on:
      - mongodb
      - redis
    links:
      - redis
      - mongodb
    volumes:
      - ./logs:/home/node/app/logs
    networks:
      - node-network

  consumer:
    image: devintyler2626/tesalate-processor:latest
    build: .
    env_file:
      - .env
    environment:
      - APP_TYPE=consumer
    depends_on:
      - mongodb
      - redis
      - producer
    links:
      - redis
    volumes:
      - ./logs:/home/node/app/logs
    networks:
      - node-network


  mongodb:
    image: mongo:4.4
    ports:
      - '27021:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

  redis:
    image: redis:6.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '6379'
    healthcheck:
      test: redis-cli ping
      timeout: 5s
      retries: 5
    networks:
      - node-network
    volumes: 
      - dbdata:/data

volumes:
  dbdata:
  redis:

networks:
  node-network:
    driver: bridge