
version: '3.9'

services:
  processor:
    image: devintyler2626/tesalate-processor:latest
    build: .
    env_file:
      - .env
    ports:
      - '4400:4400'
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./logs:/home/node/app/logs
    networks:
      - node-network

  mongodb:
    image: mongo:5.0.6
    ports:
      - '27021:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    healthcheck:
      test: ["cmd", "redis-cli", "ping"]
      timeout: 5s
      retries: 5
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data

volumes:
  dbdata:
  redis:

networks:
  node-network:
    driver: bridge